INSERT INTO countries (id, name) VALUES (1, 'USA');
INSERT INTO countries (id, name) VALUES (2, 'France');

--INSERT INTO users (userId,id,title,body) VALUES (1,1,'titlestr','bodystr');
--INSERT INTO users (id,title,body) VALUES (1,'titlestr','bodystr');
INSERT INTO users (id,userid,title,body) VALUES (1,1,'sunt aut facere repellat provident occaecati excepturi optio reprehenderit','est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla');
INSERT INTO users (id,userid,title,body) VALUES (2,1,'qui est esse','quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto');
INSERT INTO users (id,userid,title,body) VALUES (3,1,'ea molestias quasi exercitationem repellat qui ipsa sit aut','et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut');
INSERT INTO users (id,userid,title,body) VALUES (4,1,'eum et est occaecati','ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit');
INSERT INTO users (id,userid,title,body) VALUES (5,1,'nesciunt quas odio','repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque');
INSERT INTO users (id,userid,title,body) VALUES (6,1,'sunt aut facere repellat provident occaecati excepturi optio reprehenderit','ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae');
INSERT INTO users (id,userid,title,body) VALUES (7,1,'magnam facilis autem','dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas');
INSERT INTO users (id,userid,title,body) VALUES (8,1,'dolorem dolore est ipsam','dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae');
INSERT INTO users (id,userid,title,body) VALUES (9,1,'nesciunt iure omnis dolorem tempora et accusantium','consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas');
INSERT INTO users (id,userid,title,body) VALUES (10,1,'optio molestias id quia eum','quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error');
INSERT INTO users (id,userid,title,body) VALUES (11,2,'et ea vero quia laudantium autem','delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi');
INSERT INTO users (id,userid,title,body) VALUES (12,2,'in quibusdam tempore odit est dolorem','itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio');
INSERT INTO users (id,userid,title,body) VALUES (13,2,'dolorum ut in voluptas mollitia et saepe quo animi','aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam');
INSERT INTO users (id,userid,title,body) VALUES (14,2,'voluptatem eligendi optio','fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum');
INSERT INTO users (id,userid,title,body) VALUES (15,2,'eveniet quod temporibus','reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae');
INSERT INTO users (id,userid,title,body) VALUES (16,2,'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio','suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta');
INSERT INTO users (id,userid,title,body) VALUES (17,2,'fugit voluptas sed molestias voluptatem provident','eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo');
INSERT INTO users (id,userid,title,body) VALUES (18,2,'voluptate et itaque vero tempora molestiae','eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam');
INSERT INTO users (id,userid,title,body) VALUES (19,2,'adipisci placeat illum aut reiciendis qui','illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas');
INSERT INTO users (id,userid,title,body) VALUES (20,2,'doloribus ad provident suscipit at','qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo');

